### ISSUE TITLE
Invalid syntax to siem_events.py

### ISSUE THREAD

**Issue by chris-y** [JoshuaSmeda/mimecast_log_collector#11]
Hi

I just migrated this to a different server and the normal events aren't coming through.  I'm getting this error:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mimecast_log_collector/run.py", line 26, in <lambda>
    p = multiprocessing.Process(target=lambda: __import__(i))
  File "/opt/mimecast_log_collector/siem_events.py", line 41
    log.warn('Rate limit hit. Sleeping for %s % str(resp_headers('X-RateLimitReset']))
                                                                  ^
SyntaxError: invalid syntax
```

This appears to be changed since I last updated.  That log.warn line and the section it is in appears to have the wrong brackets in the wrong places - but I'm not a Python expert so my attempts to fix it didn't help.
Certainly the `resp_headers(` should be `resp_headers[`, but the single quotes don't match either!

**Comment by JoshuaSmeda** [comment]
Hi Chris,

I don't have access to the Mimecast API to test anymore, but I've fixed the syntax issues for you  - hopefully it just works now.

`checkout` the `js_fix_429` branch and give it a test, let me know if it works? - https://github.com/JoshuaSmeda/mimecast_log_collector/tree/js_fix_429

Changelog:
https://github.com/JoshuaSmeda/mimecast_log_collector/commit/92ada0871451885f1a315532def9bb55e4df9c54

**Comment by chris-y** [comment]
That works great, thanks!

**Comment by JoshuaSmeda** [comment]
Great, thanks! I've merged to `master`
